[profile.default]
ffi = false
fuzz_runs = 256
optimizer = true
optimizer_runs = 999999
verbosity = 1
libs = ["lib"]
src = "contracts/"
test = 'test'
out = 'out'
cache_path  = 'forge-cache'
solc = '0.8.16' # set solc version
# auto_detect_solc = true
