name: Formatting and Linting

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  format-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            forge-cache
            out
          key: ${{ runner.OS }}-contracts-${{ hashFiles('contracts/*.sol', 'contracts/**/*.sol') }}
          restore-keys: |
            ${{ runner.OS }}-contracts-

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Formatting
        run: forge fmt --check
