name: Slither Analysis

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  analyze:
    runs-on: ubuntu-latest
    env:
      NODOCKER: 1
    steps:
      - uses: actions/checkout@v3

      - uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip' # caching pip dependencies
      - run: pip install -r requirements.txt

      - name: Compile and create artifacts
        run: forge build

      - name: Prepare slither
        run: |
          chmod +x ./slither.sh

      - name: Run slither
        run: ./slither.sh
