name: Fuzzing

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - 'contracts/**'
      - 'test/**'

jobs:
  fuzzing:
    name: Foundry test

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            forge-cache
            out
          key: ${{ runner.OS }}-contracts-${{ hashFiles('contracts/*.sol', 'contracts/**/*.sol') }}
          restore-keys: |
            ${{ runner.OS }}-contracts-

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Installing dependencies
        run: yarn install --prefer-offline --frozen-lockfile

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install pip3
        run: |
          python -m pip install --upgrade pip

      - name: Install vyper
        run: |
          pip3 install vyper==0.3.3

      - name: Run tests
        run: forge test --fork-url $MAINNET_RPC_URL -vvv
        env:
          MAINNET_RPC_URL: ${{ secrets.ETH_NODE_URI_MAINNET }}
          FORK_NUMBER: ${{ secrets.FORK_NUMBER }}
